dynamic menus/Controllers/MenusController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DynamicMenus.Models;

namespace DynamicMenus.Controllers
{
    public class MenusController : Controller
    {
        private MenuDBContext DB = new MenuDBContext();




        #region Menus List
        // GET: Menus
        public ActionResult Index()
        {
            var Menus = DB.Menus.Include(m => m.Parent);
            return View(Menus.ToList());
        }




        #endregion

        #region Header Menu

        // render a partial view of header menu
        [ChildActionOnly]
        public ActionResult MenuPages()
        {
            try
            {
                //show only the visible menus
                var Menus = DB.Menus.Where(x => x.IsMenuVisible == true).Include(m => m.Parent);

                return PartialView("_HeaderMenu", Menus.ToList());
            }
            catch
            {
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");
            }
        }

        #endregion

        #region Internal Pages 
        // internal links



        public ActionResult OurProducts()
        {
            try
            {
                return View();
            }
            catch
            {
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");
            }
        }

        public ActionResult OurVision()
        {
            try
            {
                return View();
            }
            catch
            {
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");
            }
        }

        public ActionResult SalesJobs()
        {
            try
            {
                return View();
            }
            catch
            {
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");
            }
        }


        #endregion

        #region Error Page
        // this action renders a page that is used to handle exception in productoin environment

        public ActionResult ErrorPage()
        {
            return View();
        }
        #endregion

        #region Add New Menu
        public ActionResult Create()
        {
            try
            {
                ViewBag.ParentId = new SelectList(DB.Menus.Where(x => x.Parent == null), "MenuId", "MenuName");
                return View();
            }
            catch
            {
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");
            }
        }

        
        // POST: Menus/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MenuId,MenuName,MenuLink,ParentId,IsMenuVisible,IsLinkBlankPage")] Menu MenuModel)
        {

            try { 

            if (ModelState.IsValid)
            {
                DB.Menus.Add(MenuModel);
                DB.SaveChanges();
                return RedirectToAction("Index");
            }

            // this viewbag is filled with selectlist data of parent menu
            ViewBag.ParentId = new SelectList(DB.Menus.Where(x => x.Parent == null), "MenuId", "MenuName", MenuModel.ParentId);
            return View(MenuModel);

            }

            catch
            {
                // redirect to error page
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");

            }
        }
        #endregion

        #region Edit Menu  Information
        // GET: Menus/Edit/5
        public ActionResult Edit(int? Id)
        {
            try
            {

                if (Id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Menu MenuModel = DB.Menus.Find(Id);
                if (MenuModel == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ParentId = new SelectList(DB.Menus.Where(x => x.Parent == null), "MenuId", "MenuName", MenuModel.ParentId);
                return View(MenuModel);
            }

            catch
            {
                // redirect to error page
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");

            }
        }

        // POST: Menus/Edit/5
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MenuId,MenuName,MenuLink,ParentId,IsMenuVisible,IsLinkBlankPage")] Menu MenuModel)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    DB.Entry(MenuModel).State = EntityState.Modified;
                    DB.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ParentId = new SelectList(DB.Menus.Where(x => x.Parent == null), "MenuId", "MenuName", MenuModel.ParentId);
                return View(MenuModel);
            }
            catch
            {
                // redirect to error page
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");

            }
        }

        #endregion

        #region Delete Menu
        
        // GET: Menus/Delete/5
        public ActionResult Delete(int? Id)
        {

            // attention ! you must delete the parent menu before deleting its children
            try
            {
                if (Id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Menu MenuModel = DB.Menus.Find(Id);
                if (MenuModel == null)
                {
                    return HttpNotFound();
                }
                return View(MenuModel);
            }

            catch
            {
                // redirect to error page
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");

            }
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {

            // attention ! you must delete the parent menu before deleting its children
            try
            {
                Menu MenuModel = DB.Menus.Include(m => m.SubMenus).Where(x=>x.MenuId==Id).FirstOrDefault();
                if (MenuModel.SubMenus.Any())
                {

                    ViewBag.ErrorDeleteParent = "You Can Not Delete A Menu That Has Children , Please Delete Its Children First";
                    return View(MenuModel);

                }
                DB.Menus.Remove(MenuModel);
                DB.SaveChanges();
                return RedirectToAction("Index");

            }
            catch
            {
                // redirect to error page
                // you can also log the exception if you want that
                return RedirectToAction("ErrorPage");

            }
        }

        #endregion

    }
}

dynamic menus/Views/Shared/_HeaderMenu.cshtml
@model IEnumerable<DynamicMenus.Models.Menu>

@{
    ViewBag.Title = "MenuPages";
}

<!-- bootstrap 5 header , dynamic menu inside -->

<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom bg-light">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4"> Site Name</span>
    </a>

    <!-- dynamic menu in ul  -->

    <ul class="nav nav-pills">

        @foreach (var item in Model)
        {

            <!-- display the parent menus   -->
            if (item.Parent == null)
            {

                if (item.SubMenus == null)
                {


                    <!-- target is blank  -->
                    if (item.IsLinkBlankPage == true)
                    {
                        <!-- if the menu has no children , it will have diffrent look , will have no dropdown style  -->
                        <li class="nav-item"><a target="_blank" href=" @Url.Content(item.MenuLink)" class="nav-link">  @Html.DisplayFor(modelItem => item.MenuName)</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a href=" @Url.Content(item.MenuLink)" class="nav-link">  @Html.DisplayFor(modelItem => item.MenuName)</a></li>

                    }
                }
                else
                {
                    <!-- if the menu has children , it will have a dropdown style -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="@Url.Content(item.MenuLink)" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @Html.DisplayFor(modelItem => item.MenuName)
                        </a>


                        <!-- display sub menus 2nd level -->
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @foreach (var SubMenu in item.SubMenus)
                            {

                                if (SubMenu.SubMenus == null)
                                {
                                    <!-- target is blank  -->
                                    if (SubMenu.IsLinkBlankPage == true)
                                    {
                                        <li><a class="dropdown-item" target="_blank" href="@Url.Content(SubMenu.MenuLink)">@SubMenu.MenuName</a></li>

                                    }
                                    else
                                    {

                                        <li><a class="dropdown-item" href="@Url.Content(SubMenu.MenuLink)">@SubMenu.MenuName</a></li>
                                    }

                                    @*<li><hr class="dropdown-divider"></li>*@
                                }



                            }
                        </ul>
                    </li>
                }
            }
        }


    </ul>
</header>

dynamic menus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dynamic Menu App</title>

    <!--bootsrap 5 css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--site css -->
    <link href="~/Style/Site.css" rel="stylesheet" />
</head>
<body>
    @{
        Html.RenderAction("MenuPages", "Menus");
    }

    @RenderBody()


    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <!--bootsrap 5 javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</body>
</html>